---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-plugin
  namespace: {{ prometheus-namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-plugin
  namespace: {{ prometheus-namespace }}
  labels:
    k8s-app: prometheus-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-plugin
  template:
    metadata:
      labels:
        k8s-app: prometheus-plugin
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: prometheus-plugin
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      containers:
      - name: prometheus-plugin
        image: aixeshunter/prometheus-plugin:v0.1
        command:
        - /prometheus-plugin
        - run
        - --period=1m
        - --namespace={{ prometheus-namespace }}
        - --v=4
        volumeMounts:
        - name: timezone
          mountPath: "/etc/localtime"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      volumes:
      - name: timezone
        hostPath:
          path: "/etc/localtime"
